/** Eine Art mit allen Feldern, die die Abschnitte des Editors bearbeiten. */
export const SECTION_SPECIES: Record<string, unknown> = {
  id: 'art-eins',
  slug: 'boletus-edulis',
  name: 'Steinpilz',
  scientificName: 'Boletus edulis',
  genusName: 'Boletus',
  group: 'bolete',
  edibility: 'edible',
  protection: 'none',
  forecastEnabled: true,
  updatedAt: '2026-09-10T10:00:00+02:00',
  periodStartMonth: 6,
  periodEndMonth: 10,
  periodPeakMonth: null,
  hymeniumType: 'gills',
  gillAttachment: 'free',
  gillSpacing: 'close',
  gillEdge: 'smooth',
  smellText: 'Frisch angenehm pilzig.',
  names: [],
  measurements: [
    {
      part: 'cap',
      measurements: [{ dimension: 'width', unit: 'cm', low: 4, high: 20 }],
    },
  ],
  colours: [{ part: 'gills', mode: 'single', colours: [{ name: 'rosa', hex: '#e8c8cf' }] }],
  colourChanges: [],
  capFeatures: [],
  capMargins: [],
  stemFeatures: [],
  traits: [],
  sources: [],
  seasons: [],
  terms: [{ term: { id: 't-1', slug: 'mushroomy', name: 'pilzig', kind: 'smell' }, fromExperience: false }],
  lookalikes: [],
};
