package season

// Art is one entry of ARTEN: a latin name and its German name.
type Art struct{ Latin, German string }

// Arten are, in this order, the
// collectable species of the app. The season table lists them in this order.
var Arten = []Art{
	{"Boletus edulis", "Steinpilz"},
	{"Boletus reticulatus", "Sommersteinpilz"},
	{"Boletus pinophilus", "Kiefernsteinpilz"},
	{"Boletus aereus", "Schwarzhütiger Steinpilz"},
	{"Imleria badia", "Maronenröhrling"},
	{"Leccinum scabrum", "Birkenpilz"},
	{"Leccinum versipelle", "Birken-Rotkappe"},
	{"Leccinum aurantiacum", "Espen-Rotkappe"},
	{"Suillus luteus", "Butterpilz"},
	{"Suillus grevillei", "Goldröhrling"},
	{"Suillus bovinus", "Kuhröhrling"},
	{"Suillus granulatus", "Körnchenröhrling"},
	{"Xerocomellus chrysenteron", "Rotfußröhrling"},
	{"Xerocomus subtomentosus", "Ziegenlippe"},
	{"Neoboletus erythropus", "Flockenstieliger Hexenröhrling"},
	{"Suillellus luridus", "Netzstieliger Hexenröhrling"},
	{"Butyriboletus appendiculatus", "Anhängselröhrling"},
	{"Cantharellus cibarius", "Pfifferling"},
	{"Craterellus tubaeformis", "Trompetenpfifferling"},
	{"Craterellus cornucopioides", "Totentrompete"},
	{"Craterellus lutescens", "Gelbstieliger Trompetenpfifferling"},
	{"Hydnum repandum", "Semmelstoppelpilz"},
	{"Hydnum rufescens", "Rotgelber Stoppelpilz"},
	{"Lactarius deliciosus", "Edelreizker"},
	{"Lactarius deterrimus", "Fichtenreizker"},
	{"Lactarius salmonicolor", "Lachsreizker"},
	{"Lactarius volemus", "Brätling"},
	{"Russula cyanoxantha", "Frauentäubling"},
	{"Russula vesca", "Speisetäubling"},
	{"Russula virescens", "Grüngefelderter Täubling"},
	{"Russula claroflava", "Gelber Graustieltäubling"},
	{"Macrolepiota procera", "Parasol"},
	{"Macrolepiota mastoidea", "Zitzen-Riesenschirmling"},
	{"Chlorophyllum rhacodes", "Safranschirmling"},
	{"Agaricus campestris", "Wiesenchampignon"},
	{"Agaricus arvensis", "Schafchampignon"},
	{"Agaricus augustus", "Riesenchampignon"},
	{"Agaricus sylvaticus", "Waldchampignon"},
	{"Coprinus comatus", "Schopftintling"},
	{"Lycoperdon perlatum", "Flaschenbovist"},
	{"Calvatia gigantea", "Riesenbovist"},
	{"Lycoperdon utriforme", "Hasenbovist"},
	{"Clitocybe nebularis", "Nebelkappe"},
	{"Lepista nuda", "Violetter Rötelritterling"},
	{"Lepista personata", "Lilastieliger Rötelritterling"},
	{"Infundibulicybe geotropa", "Mönchskopf"},
	{"Armillaria mellea", "Honiggelber Hallimasch"},
	{"Armillaria ostoyae", "Dunkler Hallimasch"},
	{"Armillaria gallica", "Gelbschuppiger Hallimasch"},
	{"Kuehneromyces mutabilis", "Stockschwämmchen"},
	{"Flammulina velutipes", "Samtfußrübling"},
	{"Pleurotus ostreatus", "Austernseitling"},
	{"Pleurotus pulmonarius", "Lungenseitling"},
	{"Hericium erinaceus", "Igelstachelbart"},
	{"Hericium coralloides", "Ästiger Stachelbart"},
	{"Fistulina hepatica", "Ochsenzunge"},
	{"Laetiporus sulphureus", "Schwefelporling"},
	{"Sparassis crispa", "Krause Glucke"},
	{"Grifola frondosa", "Klapperschwamm"},
	{"Meripilus giganteus", "Riesenporling"},
	{"Cerioporus squamosus", "Schuppiger Porling"},
	{"Marasmius oreades", "Nelkenschwindling"},
	{"Calocybe gambosa", "Maipilz"},
	{"Amanita rubescens", "Perlpilz"},
	{"Amanita fulva", "Fuchsiger Scheidenstreifling"},
	{"Morchella esculenta", "Speisemorchel"},
	{"Morchella elata", "Spitzmorchel"},
	{"Mitrophora semilibera", "Käppchenmorchel"},
	{"Verpa bohemica", "Böhmische Verpel"},
	{"Auricularia auricula-judae", "Judasohr"},
	{"Tricholoma terreum", "Erdritterling"},
	{"Tricholoma portentosum", "Schwarzfaseriger Ritterling"},
	{"Hygrophorus marzuolus", "Märzschneckling"},
	{"Mucidula mucida", "Buchen-Schleimrübling"},
	{"Gomphidius glutinosus", "Kuhmaul"},
	{"Chroogomphus rutilus", "Kupferroter Gelbfuß"},
	{"Cortinarius caperatus", "Reifpilz"},
	{"Lyophyllum decastes", "Büscheliger Rasling"},
	{"Clitopilus prunulus", "Mehlräsling"},
	{"Albatrellus ovinus", "Schafporling"},
	{"Sarcodon imbricatus", "Habichtspilz"},
	{"Aleuria aurantia", "Orangebecherling"},
	{"Leucoagaricus leucothites", "Rosablättriger Egerlingsschirmling"},
	{"Entoloma clypeatum", "Schildrötling"},
	{"Lepista flaccida", "Fuchsiger Rötelritterling"},
}

// LatinNames gives the latin names of Arten in order.
func LatinNames() []string {
	out := make([]string, len(Arten))
	for i, a := range Arten {
		out[i] = a.Latin
	}
	return out
}
