/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportMyData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteMyData"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSpeciesBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSpecies"];
        put?: never;
        post: operations["createSpecies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["SpeciesSlug"];
            };
            cookie?: never;
        };
        get: operations["getSpecies"];
        put: operations["replaceSpecies"];
        post?: never;
        delete: operations["deleteSpecies"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{slug}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["SpeciesSlug"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setSpeciesForecast"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{slug}/counts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["SpeciesSlug"];
            };
            cookie?: never;
        };
        get: operations["getSpeciesCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxa/{rank}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTaxonPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTerms"];
        put?: never;
        post: operations["createTerm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateTerm"];
        trace?: never;
    };
    "/terms/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mergeTerm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFinds"];
        put?: never;
        post: operations["createFind"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getFind"];
        /** @description Creates the find with this id, or replaces it. Idempotent for the offline queue. */
        put: operations["putFind"];
        post?: never;
        delete: operations["deleteFind"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finds/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviewFind"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finds/reviews/accept-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptAllOpenFinds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMarkers"];
        put?: never;
        post: operations["createMarker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getMarker"];
        /** @description Creates the marker with this id, or replaces it. Idempotent for the offline queue. */
        put: operations["putMarker"];
        post?: never;
        delete: operations["deleteMarker"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listZones"];
        put?: never;
        post: operations["createZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getZone"];
        /** @description Creates the zone with this id, or replaces it. Idempotent for the offline queue. */
        put: operations["putZone"];
        post?: never;
        delete: operations["deleteZone"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones/{id}/value": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getZoneValue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/combinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCombinations"];
        put?: never;
        post: operations["createCombination"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/combinations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getCombination"];
        /** @description Creates the combination with this id, or replaces it. Idempotent for the offline queue. */
        put: operations["putCombination"];
        post?: never;
        delete: operations["deleteCombination"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPhotos"];
        put?: never;
        post: operations["createPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getPhoto"];
        put?: never;
        post?: never;
        delete: operations["deletePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/{size}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPhotoFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approvePhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/rejection": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejectPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/lead": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setLeadPhoto"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/texts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTexts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/texts/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["putText"];
        post?: never;
        delete: operations["resetText"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoles"];
        put?: never;
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getRole"];
        put?: never;
        post?: never;
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch: operations["updateRole"];
        trace?: never;
    };
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPeople"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getPerson"];
        put?: never;
        post?: never;
        delete: operations["deletePerson"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setPersonRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPipelineRuns"];
        put?: never;
        post: operations["createPipelineRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getPipelineRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/pipeline-runs/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claimPipelineRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/pipeline-runs/{id}/species/{speciesId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportPipelineRunSpecies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/pipeline-runs/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finishPipelineRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/training-finds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTrainingFinds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            /** @description Machine-readable key, for example not_found or last_admin. */
            code: string;
            detail?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            field: string;
            code: string;
        };
        Health: {
            status: string;
        };
        Config: {
            oidcIssuer: string;
            oidcClientId: string;
            origin: string;
            version: string;
        };
        Me: {
            /** Format: uuid */
            id: string;
            sub: string;
            email: string;
            name: string;
        };
        MyPermissions: {
            permissions: components["schemas"]["Permission"][];
        };
        AccountExport: {
            me: components["schemas"]["Me"];
            finds: components["schemas"]["Find"][];
            markers: components["schemas"]["Marker"][];
            zones: components["schemas"]["Zone"][];
            combinations: components["schemas"]["Combination"][];
            photos: components["schemas"]["Photo"][];
        };
        /** @enum {string} */
        Permission: "species.edit" | "image.review" | "find.review" | "role.manage" | "role.assign" | "text.edit" | "run.manage";
        /** @enum {string} */
        Area: "species" | "interface" | "access" | "data";
        PermissionEntry: {
            key: components["schemas"]["Permission"];
            area: components["schemas"]["Area"];
        };
        /** @enum {string} */
        Visibility: "private" | "shared";
        /** @enum {string} */
        ReviewState: "open" | "accepted" | "rejected";
        /** @enum {string} */
        ReviewDecision: "accepted" | "rejected";
        /** @enum {string} */
        PhotoState: "private" | "submitted" | "approved" | "rejected";
        /** @enum {string} */
        RunKind: "training" | "render" | "full";
        /** @enum {string} */
        RunState: "queued" | "running" | "finished" | "failed";
        /** @enum {string} */
        ColourMode: "single" | "gradient" | "distinct";
        /** @enum {string} */
        TriggerGroup: "mechanical" | "reagent" | "environment";
        /** @enum {string} */
        Edibility: "edible" | "conditionally_edible" | "inedible" | "poisonous" | "deadly";
        /** @enum {string} */
        Protection: "none" | "personal_use" | "strict";
        /** @enum {string} */
        BodyPart: "cap" | "stem" | "gills" | "flesh" | "spore_print" | "tubes" | "pores";
        /** @enum {string} */
        Dimension: "width" | "height" | "thickness" | "length";
        /** @enum {string} */
        Unit: "cm" | "mm" | "um";
        /** @enum {string} */
        Speed: "immediate" | "30s" | "1min" | "3min" | "longer" | "permanent";
        /** @enum {string} */
        Rule: "intersection" | "graded";
        /** @enum {string} */
        Condition: "below" | "above" | "between";
        /** @enum {string} */
        TaxonRank: "division" | "class" | "order" | "family" | "genus";
        /** @enum {string} */
        Group: "bolete" | "rough_stemmed_bolete" | "slippery_jack" | "chanterelle" | "hedgehog" | "milkcap" | "brittlegill" | "parasol" | "agaricus" | "inkcap" | "puffball" | "funnel" | "blewit" | "honey_fungus" | "scalycap" | "toughshank" | "porcelain" | "oyster" | "lions_mane" | "polypore" | "cauliflower" | "knight" | "parachute" | "woodwax" | "amanita" | "morel" | "jelly_ear" | "spike" | "webcap" | "domecap" | "pinkgill" | "spine_fungus" | "cup_fungus";
        /** @enum {string} */
        Frequency: "very_common" | "common" | "scattered" | "rare" | "very_rare";
        /** @enum {string} */
        RedListStatus: "critically_endangered" | "endangered" | "vulnerable" | "unknown_extent" | "extremely_rare" | "near_threatened" | "data_deficient";
        /** @enum {string} */
        HymeniumType: "gills" | "tubes" | "pores" | "spines" | "folds";
        /** @enum {string} */
        GillAttachment: "free" | "adnate" | "emarginate" | "decurrent";
        /** @enum {string} */
        GillSpacing: "close" | "normal" | "distant";
        /** @enum {string} */
        GillEdge: "smooth" | "serrate" | "ciliate";
        /** @enum {string} */
        CapShape: "hemispherical" | "convex" | "flat" | "depressed" | "funnel" | "conical" | "bell" | "egg" | "spherical" | "shell" | "pear" | "club" | "cylindrical";
        /** @enum {string} */
        CapFeature: "umbonate" | "hygrophanous" | "zoned" | "sunken" | "irregular" | "navelled";
        /** @enum {string} */
        CapMargin: "inrolled" | "wavy" | "striate" | "cracked" | "fringed" | "incurved" | "overhanging" | "sharp" | "lobed";
        /** @enum {string} */
        StemFeature: "ring" | "bulb" | "hollow" | "fibrous" | "flocked" | "solid" | "banded" | "netted" | "hairy" | "rooting" | "striate" | "volva" | "brittle";
        /** @enum {string} */
        Phase: "young" | "old";
        /** @enum {string} */
        Season: "spring" | "summer" | "autumn" | "winter";
        /** @enum {string} */
        TermKind: "smell" | "taste" | "tree" | "trigger";
        /** @enum {string} */
        NameKind: "common" | "synonym";
        /** @enum {string} */
        SourceScope: "profile" | "further";
        /** @enum {string} */
        TraitKey: "fruitbody" | "cap" | "tubes" | "gills" | "folds" | "spines" | "pores" | "milk" | "stem" | "flesh" | "smell" | "taste" | "spore_print" | "reagents" | "habitat" | "season" | "edibility" | "protection";
        /** @enum {string} */
        Licence: "own" | "cc0" | "cc_by_4" | "cc_by_sa_4" | "public_domain";
        /** @enum {string} */
        PhotoSize: "thumb" | "list" | "full";
        /** @enum {string} */
        MarkerColour: "green" | "brown" | "blue" | "red" | "gold" | "grey";
        HexColour: string;
        GeoPoint: {
            /** @constant */
            type: "Point";
            coordinates: number[];
        };
        GeoPolygon: {
            /** @constant */
            type: "Polygon";
            coordinates: number[][][];
        };
        ColourValue: {
            name: string;
            hex: components["schemas"]["HexColour"];
        };
        TermRef: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
        };
        ColourGroup: {
            part: components["schemas"]["BodyPart"];
            mode: components["schemas"]["ColourMode"];
            colours: components["schemas"]["ColourValue"][];
        };
        ColourChange: {
            part: components["schemas"]["BodyPart"];
            kind: components["schemas"]["TriggerGroup"];
            from?: components["schemas"]["ColourValue"] | null;
            to: components["schemas"]["ColourValue"];
            speed?: components["schemas"]["Speed"] | null;
            triggers: components["schemas"]["TermRef"][];
        };
        Measurement: {
            dimension: components["schemas"]["Dimension"];
            unit: components["schemas"]["Unit"];
            low: number;
            high: number;
            rareLow?: number | null;
            rareHigh?: number | null;
            description?: string | null;
        };
        MeasurementGroup: {
            part: components["schemas"]["BodyPart"];
            measurements: components["schemas"]["Measurement"][];
        };
        CapFeatureEntry: {
            feature: components["schemas"]["CapFeature"];
            phase: components["schemas"]["Phase"];
        };
        CapMarginEntry: {
            margin: components["schemas"]["CapMargin"];
            phase: components["schemas"]["Phase"];
        };
        StemFeatureEntry: {
            feature: components["schemas"]["StemFeature"];
            phase: components["schemas"]["Phase"];
        };
        Trait: {
            key: components["schemas"]["TraitKey"];
            text: string;
        };
        SourceEntry: {
            scope: components["schemas"]["SourceScope"];
            title: string;
            url: string;
            /** Format: date */
            checkedOn: string;
        };
        SpeciesNameEntry: {
            name: string;
            kind: components["schemas"]["NameKind"];
        };
        SpeciesTermEntry: {
            term: components["schemas"]["TermRef"];
            fromExperience: boolean;
        };
        Lookalike: {
            slug: string;
            name: string;
            scientificName: string;
            edibility: components["schemas"]["Edibility"];
            warning?: string | null;
            capColours: components["schemas"]["ColourValue"][];
            difference?: string | null;
        };
        SpeciesSummary: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            scientificName: string;
            taxonId?: string | null;
            group: components["schemas"]["Group"];
            edibility: components["schemas"]["Edibility"];
            protection: components["schemas"]["Protection"];
            collectable: boolean;
            forecastEnabled: boolean;
            leadPhotoId?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        SpeciesWrite: {
            name: string;
            scientificName: string;
            taxonId?: string | null;
            group: components["schemas"]["Group"];
            edibility: components["schemas"]["Edibility"];
            collectable?: boolean;
            marketable?: boolean;
            valueRating?: number | null;
            frequency?: components["schemas"]["Frequency"] | null;
            redList?: components["schemas"]["RedListStatus"] | null;
            description?: string | null;
            warning?: string | null;
            edibilityNote?: string | null;
            protection: components["schemas"]["Protection"];
            protectionNote?: string | null;
            protectionSource?: string | null;
            periodStartMonth?: number | null;
            periodEndMonth?: number | null;
            periodPeakMonth?: number | null;
            smellText?: string | null;
            tasteText?: string | null;
            hymeniumType?: components["schemas"]["HymeniumType"] | null;
            gillAttachment?: components["schemas"]["GillAttachment"] | null;
            gillSpacing?: components["schemas"]["GillSpacing"] | null;
            gillEdge?: components["schemas"]["GillEdge"] | null;
            capShapeYoung?: components["schemas"]["CapShape"] | null;
            capShapeOld?: components["schemas"]["CapShape"] | null;
            names?: components["schemas"]["SpeciesNameEntry"][];
            measurements?: components["schemas"]["MeasurementGroup"][];
            colours?: components["schemas"]["ColourGroup"][];
            colourChanges?: components["schemas"]["ColourChange"][];
            capFeatures?: components["schemas"]["CapFeatureEntry"][];
            capMargins?: components["schemas"]["CapMarginEntry"][];
            stemFeatures?: components["schemas"]["StemFeatureEntry"][];
            traits?: components["schemas"]["Trait"][];
            sources?: components["schemas"]["SourceEntry"][];
            seasons?: components["schemas"]["Season"][];
            terms?: components["schemas"]["SpeciesTermEntry"][];
            lookalikes?: {
                slug: string;
                difference: string;
            }[];
        };
        Species: components["schemas"]["SpeciesSummary"] & {
            description?: string | null;
            warning?: string | null;
            marketable?: boolean;
            valueRating?: number | null;
            frequency?: components["schemas"]["Frequency"] | null;
            redList?: components["schemas"]["RedListStatus"] | null;
            edibilityNote?: string | null;
            protectionNote?: string | null;
            protectionSource?: string | null;
            periodStartMonth?: number | null;
            periodEndMonth?: number | null;
            periodPeakMonth?: number | null;
            smellText?: string | null;
            tasteText?: string | null;
            hymeniumType?: components["schemas"]["HymeniumType"] | null;
            gillAttachment?: components["schemas"]["GillAttachment"] | null;
            gillSpacing?: components["schemas"]["GillSpacing"] | null;
            gillEdge?: components["schemas"]["GillEdge"] | null;
            capShapeYoung?: components["schemas"]["CapShape"] | null;
            capShapeOld?: components["schemas"]["CapShape"] | null;
            names: components["schemas"]["SpeciesNameEntry"][];
            measurements: components["schemas"]["MeasurementGroup"][];
            colours: components["schemas"]["ColourGroup"][];
            colourChanges: components["schemas"]["ColourChange"][];
            capFeatures: components["schemas"]["CapFeatureEntry"][];
            capMargins: components["schemas"]["CapMarginEntry"][];
            stemFeatures: components["schemas"]["StemFeatureEntry"][];
            traits: components["schemas"]["Trait"][];
            sources: components["schemas"]["SourceEntry"][];
            seasons: components["schemas"]["Season"][];
            terms: components["schemas"]["SpeciesTermEntry"][];
            lookalikes: components["schemas"]["Lookalike"][];
        };
        SpeciesCounts: {
            records: number;
            finds: number;
            photos: number;
        };
        SpeciesPage: {
            items: components["schemas"]["SpeciesSummary"][];
            nextCursor: string | null;
        };
        SpeciesBundle: {
            items: components["schemas"]["Species"][];
        };
        TaxonStep: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            rank: components["schemas"]["TaxonRank"];
        };
        TaxonChild: components["schemas"]["TaxonStep"] & {
            speciesCount: number;
        };
        TaxonPage: components["schemas"]["TaxonStep"] & {
            description?: string | null;
            path: components["schemas"]["TaxonStep"][];
            siblings: components["schemas"]["TaxonStep"][];
            children: components["schemas"]["TaxonChild"][];
            species: components["schemas"]["SpeciesSummary"][];
            speciesCount: number;
        };
        Term: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["TermKind"];
            group?: components["schemas"]["TriggerGroup"] | null;
            slug: string;
            name: string;
            position: number;
        };
        TermCreate: {
            kind: components["schemas"]["TermKind"];
            group?: components["schemas"]["TriggerGroup"] | null;
            slug: string;
            name: string;
            position?: number;
        };
        TermUpdate: {
            name?: string;
            group?: components["schemas"]["TriggerGroup"] | null;
            position?: number;
        };
        Find: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerId?: string;
            speciesId?: string | null;
            lat?: number;
            lon?: number;
            /** Format: date */
            foundOn?: string;
            count?: number | null;
            forTraining?: boolean;
            reviewState?: components["schemas"]["ReviewState"];
            reviewedById?: string | null;
            reviewedAt?: string | null;
            visibility?: components["schemas"]["Visibility"];
            note?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt: string;
            /** @default false */
            deleted: boolean;
        };
        FindWrite: {
            speciesId?: string | null;
            lat: number;
            lon: number;
            /** Format: date */
            foundOn: string;
            count?: number | null;
            /** @default false */
            forTraining: boolean;
            visibility?: components["schemas"]["Visibility"];
            note?: string | null;
        };
        FindPage: {
            items: components["schemas"]["Find"][];
            nextCursor: string | null;
        };
        Marker: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerId?: string;
            name?: string;
            lat?: number;
            lon?: number;
            colour?: components["schemas"]["MarkerColour"];
            visibility?: components["schemas"]["Visibility"];
            note?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt: string;
            /** @default false */
            deleted: boolean;
        };
        MarkerWrite: {
            name: string;
            lat: number;
            lon: number;
            colour?: components["schemas"]["MarkerColour"];
            visibility?: components["schemas"]["Visibility"];
            note?: string | null;
        };
        MarkerPage: {
            items: components["schemas"]["Marker"][];
            nextCursor: string | null;
        };
        Zone: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerId?: string;
            name?: string;
            polygon?: components["schemas"]["GeoPolygon"];
            areaHa?: number;
            colour?: components["schemas"]["MarkerColour"];
            visibility?: components["schemas"]["Visibility"];
            note?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt: string;
            /** @default false */
            deleted: boolean;
        };
        ZoneWrite: {
            name: string;
            polygon: components["schemas"]["GeoPolygon"];
            colour?: components["schemas"]["MarkerColour"];
            visibility?: components["schemas"]["Visibility"];
            note?: string | null;
        };
        ZonePage: {
            items: components["schemas"]["Zone"][];
            nextCursor: string | null;
        };
        ZoneValue: {
            /** Format: uuid */
            speciesId: string;
            year: number;
            week: number;
            areaMean: number;
            points: number;
            ownFinds: number;
        };
        Factor: {
            source: string;
            condition: components["schemas"]["Condition"];
            low?: number | null;
            high?: number | null;
            /** @default true */
            active: boolean;
        };
        Combination: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerId?: string;
            name?: string;
            rule?: components["schemas"]["Rule"];
            factors?: components["schemas"]["Factor"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt: string;
            /** @default false */
            deleted: boolean;
        };
        CombinationWrite: {
            name: string;
            rule: components["schemas"]["Rule"];
            factors: components["schemas"]["Factor"][];
        };
        CombinationPage: {
            items: components["schemas"]["Combination"][];
            nextCursor: string | null;
        };
        PhotoCreate: {
            /** Format: binary */
            file: string;
            /** Format: uuid */
            speciesId?: string;
            /** Format: uuid */
            findId?: string;
            photographer: string;
            licence: components["schemas"]["Licence"];
            caption?: string;
            /** Format: date */
            takenOn?: string;
        };
        Photo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerId: string;
            speciesId?: string | null;
            findId?: string | null;
            width: number;
            height: number;
            photographer: string;
            licence: components["schemas"]["Licence"];
            caption?: string | null;
            takenOn?: string | null;
            lat?: number | null;
            lon?: number | null;
            lead: boolean;
            state: components["schemas"]["PhotoState"];
            rejectReason?: string | null;
            reviewedById?: string | null;
            reviewedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PhotoPage: {
            items: components["schemas"]["Photo"][];
            nextCursor: string | null;
        };
        TextWrite: {
            locale: string;
            value: string;
        };
        TextEntry: {
            key: string;
            values: {
                [key: string]: string;
            };
            changed: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        TextsCatalogue: {
            revision: string;
            locales: string[];
            entries: components["schemas"]["TextEntry"][];
        };
        RoleBrief: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
        };
        Role: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description?: string | null;
            builtIn: boolean;
            permissions: components["schemas"]["Permission"][];
            peopleCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RoleCreate: {
            slug: string;
            name: string;
            description?: string;
            permissions?: components["schemas"]["Permission"][];
        };
        RoleUpdate: {
            name?: string;
            description?: string | null;
            permissions?: components["schemas"]["Permission"][];
        };
        RolePage: {
            items: components["schemas"]["Role"][];
            nextCursor: string | null;
        };
        Person: {
            /** Format: uuid */
            id: string;
            sub: string;
            email?: string | null;
            name?: string | null;
            roles: components["schemas"]["RoleBrief"][];
            /** Format: date-time */
            createdAt: string;
        };
        PersonPage: {
            items: components["schemas"]["Person"][];
            nextCursor: string | null;
        };
        PipelineRunSpeciesEntry: {
            /** Format: uuid */
            speciesId: string;
            state: string;
            recordCount: number;
            findCount: number;
        };
        PipelineRunSummary: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["RunKind"];
            state: components["schemas"]["RunState"];
            /** Format: date-time */
            queuedAt: string;
            startedAt?: string | null;
            finishedAt?: string | null;
            triggeredById?: string | null;
        };
        PipelineRunDetail: components["schemas"]["PipelineRunSummary"] & {
            logPath?: string | null;
            species: components["schemas"]["PipelineRunSpeciesEntry"][];
        };
        PipelineRunPage: {
            items: components["schemas"]["PipelineRunSummary"][];
            nextCursor: string | null;
        };
        TrainingFind: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            speciesId: string;
            lat: number;
            lon: number;
            /** Format: date */
            foundOn: string;
            count?: number | null;
        };
    };
    responses: {
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unprocessable Entity */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Id: string;
        SpeciesSlug: string;
        Limit40: number;
        Limit50: number;
        Cursor: string;
        Since: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyPermissions"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    exportMyData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountExport"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteMyData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSpeciesBundle: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesBundle"];
                };
            };
            /** @description Not Modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSpecies: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit40"];
                cursor?: components["parameters"]["Cursor"];
                q?: string;
                taxonId?: string;
                "edibility[]"?: components["schemas"]["Edibility"][];
                "hymenium[]"?: components["schemas"]["HymeniumType"][];
                "capShape[]"?: components["schemas"]["CapShape"][];
                "terms[]"?: string[];
                "months[]"?: number[];
                /** @description A standard colour. A species matches when the nearest standard colour of one of its catalogue colours for this part is this colour. */
                "colour[cap]"?: components["schemas"]["HexColour"];
                "colour[stem]"?: components["schemas"]["HexColour"];
                "colour[gills]"?: components["schemas"]["HexColour"];
                "colour[flesh]"?: components["schemas"]["HexColour"];
                "colour[sporePrint]"?: components["schemas"]["HexColour"];
                "colour[tubes]"?: components["schemas"]["HexColour"];
                "colour[pores]"?: components["schemas"]["HexColour"];
                /** @description Repeatable. Key is part.dimension, value is min-max in the unit of the catalogue, one side may be empty. */
                size?: {
                    [key: string]: string;
                };
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesPage"];
                };
            };
        };
    };
    createSpecies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeciesWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Species"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    getSpecies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["SpeciesSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Species"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceSpecies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["SpeciesSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeciesWrite"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Species"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
        };
    };
    deleteSpecies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["SpeciesSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setSpeciesForecast: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["SpeciesSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Species"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSpeciesCounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["SpeciesSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesCounts"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTaxonPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rank: components["schemas"]["TaxonRank"];
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonPage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listTerms: {
        parameters: {
            query?: {
                kind?: components["schemas"]["TermKind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Term"][];
                    };
                };
            };
        };
    };
    createTerm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Term"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    updateTerm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Term"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    mergeTerm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    into: string;
                };
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listFinds: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit50"];
                cursor?: components["parameters"]["Cursor"];
                since?: components["parameters"]["Since"];
                mine?: boolean;
                speciesId?: string;
                /** @description minLon,minLat,maxLon,maxLat */
                bbox?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindPage"];
                };
            };
        };
    };
    createFind: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Find"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    getFind: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Find"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putFind: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindWrite"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Find"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Find"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    deleteFind: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    reviewFind: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    decision: components["schemas"]["ReviewDecision"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Find"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    acceptAllOpenFinds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMarkers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit50"];
                cursor?: components["parameters"]["Cursor"];
                since?: components["parameters"]["Since"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkerPage"];
                };
            };
        };
    };
    createMarker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkerWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Marker"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    getMarker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Marker"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putMarker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkerWrite"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Marker"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Marker"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    deleteMarker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listZones: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit50"];
                cursor?: components["parameters"]["Cursor"];
                since?: components["parameters"]["Since"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonePage"];
                };
            };
        };
    };
    createZone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    getZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneWrite"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    deleteZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getZoneValue: {
        parameters: {
            query: {
                speciesId: string;
                year: number;
                week: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneValue"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listCombinations: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit50"];
                cursor?: components["parameters"]["Cursor"];
                since?: components["parameters"]["Since"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CombinationPage"];
                };
            };
        };
    };
    createCombination: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CombinationWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Combination"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    getCombination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Combination"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putCombination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CombinationWrite"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Combination"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Combination"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    deleteCombination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPhotos: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit50"];
                cursor?: components["parameters"]["Cursor"];
                state?: components["schemas"]["PhotoState"];
                speciesId?: string;
                findId?: string;
                mine?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoPage"];
                };
            };
        };
    };
    createPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["PhotoCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            /** @description Payload Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    getPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deletePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPhotoFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                size: components["schemas"]["PhotoSize"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    approvePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    rejectPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    setLeadPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listTexts: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextsCatalogue"];
                };
            };
            /** @description Not Modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextWrite"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextEntry"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    resetText: {
        parameters: {
            query: {
                locale: string;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PermissionEntry"][];
                    };
                };
            };
        };
    };
    listRoles: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit50"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePage"];
                };
            };
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            422: components["responses"]["Validation"];
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPeople: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit50"];
                cursor?: components["parameters"]["Cursor"];
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonPage"];
                };
            };
        };
    };
    getPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deletePerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setPersonRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    roleIds: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listPipelineRuns: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit50"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunPage"];
                };
            };
        };
    };
    createPipelineRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    kind: components["schemas"]["RunKind"];
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunSummary"];
                };
            };
        };
    };
    getPipelineRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    claimPipelineRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunSummary"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reportPipelineRunSpecies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                speciesId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    state: string;
                    recordCount: number;
                };
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    finishPipelineRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    state: components["schemas"]["RunState"];
                    logPath?: string;
                };
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listTrainingFinds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TrainingFind"][];
                    };
                };
            };
        };
    };
}
